/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Встречи: все брони всех типов, начиная с начала сегодняшнего дня, по возрастанию. */
        get: operations["Admin_meetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Создать тип события. */
        post: operations["Admin_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Все слоты за день со всеми типами и бронями. */
        get: operations["Admin_daySlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Вернуть все типы событий. */
        get: operations["EventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Слоты за день для выбранного типа события. */
        get: operations["Guest_daySlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest/{date}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Проверка доступности слота без создания брони. */
        post: operations["Guest_availability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest/{date}/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Создание бронирования. */
        post: operations["Guest_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Ответ: все слоты и брони за день (владелец).
         * @example {
         *       "date": "2026-08-18",
         *       "slots": [
         *         {
         *           "startsAt": "2026-08-18T08:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T08:30:00Z",
         *           "status": "booked",
         *           "booking": {
         *             "id": 12,
         *             "eventType": {
         *               "id": "consultation",
         *               "name": "Консультация",
         *               "duration": 30
         *             },
         *             "guestName": "Иван Петров",
         *             "guestContact": "ivan@example.com"
         *           }
         *         },
         *         {
         *           "startsAt": "2026-08-18T09:00:00Z",
         *           "status": "free"
         *         }
         *       ]
         *     }
         */
        AdminDaySlots: {
            /** Format: date */
            date: string;
            slots: components["schemas"]["AdminSlot"][];
        };
        /**
         * @description Слот с деталями брони (вид владельца).
         * @example {
         *       "startsAt": "2026-08-18T08:30:00Z",
         *       "status": "booked",
         *       "booking": {
         *         "id": 12,
         *         "eventType": {
         *           "id": "consultation",
         *           "name": "Консультация",
         *           "duration": 30
         *         },
         *         "guestName": "Иван Петров",
         *         "guestContact": "ivan@example.com"
         *       }
         *     }
         */
        AdminSlot: {
            /** Format: date-time */
            startsAt: string;
            status: components["schemas"]["SlotStatus"];
            booking?: components["schemas"]["BookingInfo"];
        };
        /** @enum {string} */
        AvailabilityReason: "booked" | "out-of-window" | "out-of-hours" | "invalid-grid" | "already-passed";
        /** @description Проверка доступности слота. */
        AvailabilityRequest: {
            /** @description Время начала, формат HH:MM. */
            time: string;
            eventTypeId: string;
        };
        /**
         * @example {
         *       "available": true
         *     }
         */
        AvailabilityResponse: {
            available: boolean;
            reason?: components["schemas"]["AvailabilityReason"];
        };
        BadRequestError: {
            error: string;
        };
        /**
         * @description Бронирование.
         * @example {
         *       "id": 12,
         *       "eventTypeId": "consultation",
         *       "eventTypeName": "Консультация",
         *       "duration": 30,
         *       "guestName": "Иван Петров",
         *       "guestContact": "ivan@example.com",
         *       "startsAt": "2026-08-25T08:00:00Z",
         *       "endsAt": "2026-08-25T08:30:00Z"
         *     }
         */
        Booking: {
            /** Format: int32 */
            id: number;
            eventTypeId: string;
            eventTypeName: string;
            /** Format: int32 */
            duration: number;
            guestName: string;
            guestContact: string;
            /** Format: date-time */
            startsAt: string;
            /**
             * Format: date-time
             * @description Вычисляется как startsAt + duration.
             */
            endsAt: string;
        };
        /** @description Информация о брони внутри слота. */
        BookingInfo: {
            /** Format: int32 */
            id: number;
            eventType: components["schemas"]["EventType"];
            guestName: string;
            guestContact: string;
        };
        /** @description Создание бронирования. */
        BookingRequest: {
            /** @description Время начала, формат HH:MM. */
            time: string;
            eventTypeId: string;
            guestName: string;
            guestContact: string;
        };
        /**
         * @description Список встреч: все брони начиная с начала сегодняшнего дня.
         * @example {
         *       "bookings": [
         *         {
         *           "id": 12,
         *           "eventTypeId": "consultation",
         *           "eventTypeName": "Консультация",
         *           "duration": 30,
         *           "guestName": "Иван Петров",
         *           "guestContact": "ivan@example.com",
         *           "startsAt": "2026-08-25T08:00:00Z",
         *           "endsAt": "2026-08-25T08:30:00Z"
         *         },
         *         {
         *           "id": 13,
         *           "eventTypeId": "meeting",
         *           "eventTypeName": "Встреча",
         *           "duration": 60,
         *           "guestName": "Мария Иванова",
         *           "guestContact": "maria@example.com",
         *           "startsAt": "2026-09-02T10:00:00Z",
         *           "endsAt": "2026-09-02T11:00:00Z"
         *         }
         *       ]
         *     }
         */
        BookingsList: {
            bookings: components["schemas"]["Booking"][];
        };
        ConflictError: {
            error: string;
        };
        /**
         * @description Ответ: слоты за день для выбранного типа события (гость).
         * @example {
         *       "date": "2026-08-18",
         *       "eventType": {
         *         "id": "consultation",
         *         "name": "Консультация",
         *         "description": "Разбор проекта",
         *         "duration": 30
         *       },
         *       "slots": [
         *         {
         *           "startsAt": "2026-08-18T08:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T08:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T09:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T09:30:00Z",
         *           "status": "booked"
         *         },
         *         {
         *           "startsAt": "2026-08-18T10:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T10:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T11:00:00Z",
         *           "status": "booked"
         *         },
         *         {
         *           "startsAt": "2026-08-18T11:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T12:00:00Z",
         *           "status": "booked"
         *         },
         *         {
         *           "startsAt": "2026-08-18T12:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T13:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T13:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T14:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T14:30:00Z",
         *           "status": "booked"
         *         },
         *         {
         *           "startsAt": "2026-08-18T15:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T15:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T16:00:00Z",
         *           "status": "booked"
         *         },
         *         {
         *           "startsAt": "2026-08-18T16:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T17:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T17:30:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T18:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T18:30:00Z",
         *           "status": "booked"
         *         },
         *         {
         *           "startsAt": "2026-08-18T19:00:00Z",
         *           "status": "free"
         *         },
         *         {
         *           "startsAt": "2026-08-18T19:30:00Z",
         *           "status": "free"
         *         }
         *       ]
         *     }
         */
        DaySlots: {
            /** Format: date */
            date: string;
            eventType: components["schemas"]["EventType"];
            slots: components["schemas"]["Slot"][];
        };
        /**
         * @description Тип события: метка события с длительностью.
         * @example {
         *       "id": "consultation",
         *       "name": "Консультация",
         *       "description": "Разбор проекта",
         *       "duration": 30
         *     }
         */
        EventType: {
            /** @description Задаётся владельцем, уникальная строка, не более 50 символов. */
            id: string;
            /** @description Название, не более 100 символов. */
            name: string;
            /** @description Описание, не более 1000 символов. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность в минутах, кратна 30.
             */
            duration: number;
        };
        /** @description Тело запроса на создание типа события. */
        EventTypeInput: {
            /** @description Уникальный идентификатор, задаётся владельцем. */
            id: string;
            name: string;
            description?: string;
            /** Format: int32 */
            duration: number;
        };
        NotFoundError: {
            error: string;
        };
        /**
         * @description 30-минутная ячейка сетки.
         * @example {
         *       "startsAt": "2026-08-18T08:00:00Z",
         *       "status": "free"
         *     }
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало ячейки, ISO 8601.
             */
            startsAt: string;
            status: components["schemas"]["SlotStatus"];
        };
        /**
         * @description Статус 30-минутного слота. Единый для гостя и владельца.
         * @enum {string}
         */
        SlotStatus: "free" | "booked";
        ValidationError: {
            errors: components["schemas"]["ValidationErrorItem"][];
        };
        ValidationErrorItem: {
            field: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_meetings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingsList"];
                };
            };
        };
    };
    Admin_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeInput"];
            };
        };
        responses: {
            /** @description Ответ 201 Created: тип события. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    Admin_daySlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDaySlots"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Guest_daySlots: {
        parameters: {
            query: {
                eventType: string;
            };
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySlots"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Guest_availability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Guest_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description Ответ 201 Created: бронирование. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
